name: Build
on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Install npm dependencies
        run: npm ci

      - name: Build package
        run: npm run package

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: package/

      - name: Build docs
        run: npm run docs

      - name: Deploy docs
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          folder: ./dist-docs
          branch: gh-pages
